server:
  port: 8762


spring: 
  application: 
    name: vehicle-lookup-service
  cloud:
    stream:
      bindings:
        billing:
          destination: billing
          
dataservice:
  url: http://dvlasearch.appspot.com/DvlaSearch?
  apikey: DvlaSearchDemoAccount